name: l200geom

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  build-and-test:
    name: Test l200geom with Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install non-python (homebrew) dependencies
        if: ${{ matrix.os == 'macOS-latest' }}
        run: |
          brew install opencascade cgal gmp mpfr boost
      - name: Get dependencies and install l200geom
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade .[test]
      - name: Set LEGEND_METADATA variable
        run: |
          echo "LEGEND_METADATA=$GITHUB_WORKSPACE/legend-metadata" >> $GITHUB_ENV
      - name: Clone legend-metadata
        uses: actions/checkout@v4
        with:
          repository: legend-exp/legend-metadata
          fetch-depth: 0
          token: ${{ secrets.READPRIVATE }}
          path: ${{ env.LEGEND_METADATA }}
          submodules: "recursive"
      - name: Run unit tests
        run: |
          python -m pytest

  test-coverage:
    name: Calculate and upload test coverage
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set LEGEND_METADATA variable
        run: |
          echo "LEGEND_METADATA=$GITHUB_WORKSPACE/legend-metadata" >> $GITHUB_ENV
      - name: Clone legend-metadata
        uses: actions/checkout@v4
        with:
          repository: legend-exp/legend-metadata
          fetch-depth: 0
          token: ${{ secrets.READPRIVATE }}
          path: ${{ env.LEGEND_METADATA }}
          submodules: "recursive"

      - name: Generate Report
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade .[test]
          python -m pytest --cov=l200geom --cov-report=xml
      - name: Upload Coverage to codecov.io
        uses: codecov/codecov-action@v4

  build-docs:
    name: Build documentation
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set LEGEND_METADATA variable
        run: |
          echo "LEGEND_METADATA=$GITHUB_WORKSPACE/legend-metadata" >> $GITHUB_ENV
      - name: Clone legend-metadata
        uses: actions/checkout@v4
        with:
          repository: legend-exp/legend-metadata
          fetch-depth: 0
          token: ${{ secrets.READPRIVATE }}
          path: ${{ env.LEGEND_METADATA }}
          submodules: "recursive"

      - name: Setup build environment
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade .[docs]
      - name: Build docs for current ref
        run: |
          cd docs
          make clean
          make
